version: "3.8"

services:
  okadb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: okadb
      MYSQL_USER: oka
      MYSQL_PASSWORD: root123
    volumes:
      - oka:/var/lib/mysql

volumes:
  oka:
